matrix_rows <-matrix(1:20,nrow=5,byrow=TRUE)
rownames(matrix_rows) <-c("Row1","Row2","Row3","Row4","Row5")
colnames(matrix_rows) <-c("col1","col2","col3","col4")
matrix_3x3_rows <-matrix(21:29,nrow=3,byrow=TRUE)
rownames(matrix_3x3_rows) <-c("R1","R2","R3")
colnames(matrix_3x3_columns) <-c("C1","C2","C3")
matrix_2x2_cols <-matrix(c("A","B","C","D"),nrow=2,byrow=FALSE)
rownames(matrix_2x2_cols) <-c("Row1","Row2")
colnames(matrix_2x2_cols) <-c("col1","col2")
cat("5x4 matrix filled by rows : \n")
print(matrix_rows)
cat("\n 3x3 Matrix filled by rows : \n")
print(matrix_3x3_rows)
cat("\n 2x2 Matrix filled by columns : \n")
print(matrix_2x2_cols)