numeric_vector <-c(1.5,2.7,3.2,4.8)
character_vector <-c("apple","banana","cherry")
logical_vector <-c(TRUE,FALSE,TRUE,TRUE)
cat("numeric vector : \n")
print(numeric_vector)
cat("type : ",class(numeric_vector),"\n\n")
cat("character vector : \n")
print(character_vector)
cat("type : ",class(character_vector),"\n\n")
cat("logical vector : \n")
print(logical_vector)
cat("type : ",class(logical_vector),"\n")
