print("first 10 letters in lower case : ")
t=head(letters,10)
print(t)
print("last 10 letters in uppercase : ")
t=tail(LETTERS,10)
print(t)
print("letters between 22nd and 24th letters in uppercase : ")
e=tail(LETTERS[22:24])
print(e)